FROM golang:1.12.6 as builder

LABEL maintainer="Albert Owusu-Asare <albertowusuasa@gmail.com>"

ENV GO111MODULE=on

# Set the Current Working Directory inside the container
WORKDIR /customer-app

RUN go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
COPY . .

# Download all the dependencies
ENTRYPOINT ["./script/lint.sh"]